# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vectors.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rvectors.proto\x12\x04\x61uth\"\x1f\n\x10GetVectorRequest\x12\x0b\n\x03\x64oc\x18\x01 \x01(\t\"&\n\x11GetVectorResponse\x12\x11\n\tdocVector\x18\x01 \x03(\x02\x32M\n\rVectorManager\x12<\n\tGetVector\x12\x16.auth.GetVectorRequest\x1a\x17.auth.GetVectorResponseB\x14Z\x12\x61pi_with_milvus/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vectors_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\022api_with_milvus/pb'
  _globals['_GETVECTORREQUEST']._serialized_start=23
  _globals['_GETVECTORREQUEST']._serialized_end=54
  _globals['_GETVECTORRESPONSE']._serialized_start=56
  _globals['_GETVECTORRESPONSE']._serialized_end=94
  _globals['_VECTORMANAGER']._serialized_start=96
  _globals['_VECTORMANAGER']._serialized_end=173
# @@protoc_insertion_point(module_scope)
