# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vectors_pb2 as vectors__pb2


class VectorManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVector = channel.unary_unary(
                '/auth.VectorManager/GetVector',
                request_serializer=vectors__pb2.GetVectorRequest.SerializeToString,
                response_deserializer=vectors__pb2.GetVectorResponse.FromString,
                )


class VectorManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVector': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVector,
                    request_deserializer=vectors__pb2.GetVectorRequest.FromString,
                    response_serializer=vectors__pb2.GetVectorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.VectorManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VectorManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.VectorManager/GetVector',
            vectors__pb2.GetVectorRequest.SerializeToString,
            vectors__pb2.GetVectorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
