# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vectors_pb2 as vectors__pb2


class VectorManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddVector = channel.unary_unary(
                '/auth.VectorManager/AddVector',
                request_serializer=vectors__pb2.AddVectorRequest.SerializeToString,
                response_deserializer=vectors__pb2.AddVectorResponse.FromString,
                )
        self.SearchVector = channel.unary_unary(
                '/auth.VectorManager/SearchVector',
                request_serializer=vectors__pb2.SearchVectorRequest.SerializeToString,
                response_deserializer=vectors__pb2.SearchVectorResponse.FromString,
                )


class VectorManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddVector': grpc.unary_unary_rpc_method_handler(
                    servicer.AddVector,
                    request_deserializer=vectors__pb2.AddVectorRequest.FromString,
                    response_serializer=vectors__pb2.AddVectorResponse.SerializeToString,
            ),
            'SearchVector': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchVector,
                    request_deserializer=vectors__pb2.SearchVectorRequest.FromString,
                    response_serializer=vectors__pb2.SearchVectorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.VectorManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VectorManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.VectorManager/AddVector',
            vectors__pb2.AddVectorRequest.SerializeToString,
            vectors__pb2.AddVectorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.VectorManager/SearchVector',
            vectors__pb2.SearchVectorRequest.SerializeToString,
            vectors__pb2.SearchVectorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
