// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import ()

type User struct {
	ID               int64  `json:"id"`
	Name             string `json:"name"`
	PasswordHash     string `json:"password_hash"`
	Phone            string `json:"phone"`
	Email            string `json:"email"`
	PrivateContact   bool   `json:"private_contact"`
	AboutDescription string `json:"about_description"`
}
