// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Doc struct {
	UserID int64       `json:"user_id"`
	Doc    pgtype.Text `json:"doc"`
}

type User struct {
	UserID         int64     `json:"user_id"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
}
