// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, userID int64) error
	GetUser(ctx context.Context, userID int64) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUserDescription(ctx context.Context, arg UpdateUserDescriptionParams) (Doc, error)
}

var _ Querier = (*Queries)(nil)
