// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: vectors.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddVectorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VectorReq []float32 `protobuf:"fixed32,1,rep,packed,name=vectorReq,proto3" json:"vectorReq,omitempty"`
}

func (x *AddVectorRequest) Reset() {
	*x = AddVectorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vectors_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVectorRequest) ProtoMessage() {}

func (x *AddVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectors_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVectorRequest.ProtoReflect.Descriptor instead.
func (*AddVectorRequest) Descriptor() ([]byte, []int) {
	return file_vectors_proto_rawDescGZIP(), []int{0}
}

func (x *AddVectorRequest) GetVectorReq() []float32 {
	if x != nil {
		return x.VectorReq
	}
	return nil
}

type AddVectorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp bool `protobuf:"varint,1,opt,name=resp,proto3" json:"resp,omitempty"`
}

func (x *AddVectorResponse) Reset() {
	*x = AddVectorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vectors_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVectorResponse) ProtoMessage() {}

func (x *AddVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectors_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVectorResponse.ProtoReflect.Descriptor instead.
func (*AddVectorResponse) Descriptor() ([]byte, []int) {
	return file_vectors_proto_rawDescGZIP(), []int{1}
}

func (x *AddVectorResponse) GetResp() bool {
	if x != nil {
		return x.Resp
	}
	return false
}

type SearchVectorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VectorReq []float32 `protobuf:"fixed32,1,rep,packed,name=vectorReq,proto3" json:"vectorReq,omitempty"`
}

func (x *SearchVectorRequest) Reset() {
	*x = SearchVectorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vectors_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVectorRequest) ProtoMessage() {}

func (x *SearchVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectors_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVectorRequest.ProtoReflect.Descriptor instead.
func (*SearchVectorRequest) Descriptor() ([]byte, []int) {
	return file_vectors_proto_rawDescGZIP(), []int{2}
}

func (x *SearchVectorRequest) GetVectorReq() []float32 {
	if x != nil {
		return x.VectorReq
	}
	return nil
}

type SearchVectorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VectorResp []float32 `protobuf:"fixed32,1,rep,packed,name=vectorResp,proto3" json:"vectorResp,omitempty"`
}

func (x *SearchVectorResponse) Reset() {
	*x = SearchVectorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vectors_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchVectorResponse) ProtoMessage() {}

func (x *SearchVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectors_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchVectorResponse.ProtoReflect.Descriptor instead.
func (*SearchVectorResponse) Descriptor() ([]byte, []int) {
	return file_vectors_proto_rawDescGZIP(), []int{3}
}

func (x *SearchVectorResponse) GetVectorResp() []float32 {
	if x != nil {
		return x.VectorResp
	}
	return nil
}

var File_vectors_proto protoreflect.FileDescriptor

var file_vectors_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0x30, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x09, 0x76, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x22, 0x27, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70,
	0x22, 0x33, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x09, 0x76, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x22, 0x36, 0x0a, 0x14, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x02, 0x52, 0x0a, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x32, 0x94, 0x01,
	0x0a, 0x0d, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12,
	0x3c, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x16, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x41, 0x64, 0x64, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x41, 0x64, 0x64, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a,
	0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x19, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x61, 0x70, 0x69, 0x5f, 0x77, 0x69, 0x74, 0x68,
	0x5f, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_vectors_proto_rawDescOnce sync.Once
	file_vectors_proto_rawDescData = file_vectors_proto_rawDesc
)

func file_vectors_proto_rawDescGZIP() []byte {
	file_vectors_proto_rawDescOnce.Do(func() {
		file_vectors_proto_rawDescData = protoimpl.X.CompressGZIP(file_vectors_proto_rawDescData)
	})
	return file_vectors_proto_rawDescData
}

var file_vectors_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vectors_proto_goTypes = []interface{}{
	(*AddVectorRequest)(nil),     // 0: auth.AddVectorRequest
	(*AddVectorResponse)(nil),    // 1: auth.AddVectorResponse
	(*SearchVectorRequest)(nil),  // 2: auth.SearchVectorRequest
	(*SearchVectorResponse)(nil), // 3: auth.SearchVectorResponse
}
var file_vectors_proto_depIdxs = []int32{
	0, // 0: auth.VectorManager.AddVector:input_type -> auth.AddVectorRequest
	2, // 1: auth.VectorManager.SearchVector:input_type -> auth.SearchVectorRequest
	1, // 2: auth.VectorManager.AddVector:output_type -> auth.AddVectorResponse
	3, // 3: auth.VectorManager.SearchVector:output_type -> auth.SearchVectorResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vectors_proto_init() }
func file_vectors_proto_init() {
	if File_vectors_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vectors_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddVectorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vectors_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddVectorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vectors_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchVectorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vectors_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchVectorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vectors_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vectors_proto_goTypes,
		DependencyIndexes: file_vectors_proto_depIdxs,
		MessageInfos:      file_vectors_proto_msgTypes,
	}.Build()
	File_vectors_proto = out.File
	file_vectors_proto_rawDesc = nil
	file_vectors_proto_goTypes = nil
	file_vectors_proto_depIdxs = nil
}
