// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: vectors.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VectorManager_GetVector_FullMethodName = "/auth.VectorManager/GetVector"
)

// VectorManagerClient is the client API for VectorManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VectorManagerClient interface {
	GetVector(ctx context.Context, in *GetVectorRequest, opts ...grpc.CallOption) (*GetVectorResponse, error)
}

type vectorManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewVectorManagerClient(cc grpc.ClientConnInterface) VectorManagerClient {
	return &vectorManagerClient{cc}
}

func (c *vectorManagerClient) GetVector(ctx context.Context, in *GetVectorRequest, opts ...grpc.CallOption) (*GetVectorResponse, error) {
	out := new(GetVectorResponse)
	err := c.cc.Invoke(ctx, VectorManager_GetVector_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VectorManagerServer is the server API for VectorManager service.
// All implementations must embed UnimplementedVectorManagerServer
// for forward compatibility
type VectorManagerServer interface {
	GetVector(context.Context, *GetVectorRequest) (*GetVectorResponse, error)
	mustEmbedUnimplementedVectorManagerServer()
}

// UnimplementedVectorManagerServer must be embedded to have forward compatible implementations.
type UnimplementedVectorManagerServer struct {
}

func (UnimplementedVectorManagerServer) GetVector(context.Context, *GetVectorRequest) (*GetVectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVector not implemented")
}
func (UnimplementedVectorManagerServer) mustEmbedUnimplementedVectorManagerServer() {}

// UnsafeVectorManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VectorManagerServer will
// result in compilation errors.
type UnsafeVectorManagerServer interface {
	mustEmbedUnimplementedVectorManagerServer()
}

func RegisterVectorManagerServer(s grpc.ServiceRegistrar, srv VectorManagerServer) {
	s.RegisterService(&VectorManager_ServiceDesc, srv)
}

func _VectorManager_GetVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorManagerServer).GetVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorManager_GetVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorManagerServer).GetVector(ctx, req.(*GetVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VectorManager_ServiceDesc is the grpc.ServiceDesc for VectorManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VectorManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.VectorManager",
	HandlerType: (*VectorManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVector",
			Handler:    _VectorManager_GetVector_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vectors.proto",
}
