name: ci

on:
  push:
    branches: [main_go_server]
  pull_request:
    branches: [main_go_server]


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.20
      uses: actions/setup-go@v2
      with:
        go-version:^1.20
      id: go

    - name: Check out code into the go module directory
      uses: actions/checkout@v2


